spring:
  rabbitmq:
    host: dev.tss.com
    port: 5672
    username: admin
    password: njittss
    
rabbitmq: 
 topic:
  exchangeName: topidExchange
  message:
   queue: topic.queue.send
   routingKey: topic.send
  messages:
    queue: topic.queue.messages
    routingKey: topic.#