spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
rabbitmq: 
 topic:
  exchange: exchange
  message:
   queue: springboot.topic.message
   routingKey: springboot.topic.message
  messages:
    queue: springboot.topic.messages
    routingKey: springboot.topic.#