spring:
  rabbitmq:
    host: dev.tss.com
    port: 5672
    username: admin
    password: njittss
    
rabbitmq:
  fanout:
    queue:
      a: fanout.queue.a
      b: fanout.queue.b
      c: fanout.queue.c
    exchangeName: fanoutExchange